version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-30-161-203.eu-west-1.compute.amazonaws.com
            database: d6vtp1440sisis
            user: cbcsxvfostcndn
            password: c79a4fb2eeb231f8049e96767f0ceee7dccecbc0381ed699d97b40867b314fbd
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true